#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'better_image_tag'

puts BetterImageTag::InlineData.inline_data(ARGV[0], local_file: true)
